In [1]:
from __future__ import print_function
import torch  # similar to Numpy's ndarray, but can be used on a gpu

In [2]:
x = torch.empty(5, 3)  # uninitialized matrix
print(x)

tensor([[-0.0000,  0.0000, -0.0001],
        [ 0.0000, -0.0001,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0001]])


In [3]:
x = torch.rand(5, 3)  # randomly initialized matrix
print(x)

tensor([[0.3777, 0.8857, 0.0503],
        [0.9813, 0.9514, 0.6315],
        [0.9943, 0.3454, 0.1676],
        [0.9159, 0.3575, 0.3050],
        [0.9197, 0.1947, 0.4660]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)  # 0 initialized matrix of dtype long
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3]) # construct a tensor from data
print(x)

tensor([5.5000, 3.0000])


In [7]:
print(x.dtype)  
"""
so the default dtype is float32 
"""

torch.float32


In [8]:
# use a existing tensor to create a new tensor
x = x.new_ones(5, 3, dtype=torch.double)  # 1 initialized matrix of dtype double
print(x)
x = torch.randn_like(x, dtype=torch.float)   # randomly initialized based on x and override dtype
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1580,  0.1359, -1.3314],
        [ 0.2555,  0.2630, -0.0297],
        [-0.8691, -0.9252,  0.4764],
        [-0.7471, -1.6413, -0.5736],
        [-0.3603,  1.1194, -0.5668]])


In [9]:
print(x.size())
type(x.size())
"""
torch.Size is in fact a tuple, so it support all tuple operations.
"""

torch.Size([5, 3])


torch.Size

In [10]:
y = torch.rand(5,3)
z = x + y
print(z)
z = torch.add(x, y)
print(z)
torch.add(x, y, out=z)
print(z)
y.add_(x)
print(y)
"""
Any operation with an _, for excample: x.copy_(y),x.t_(), will change x
"""

tensor([[-0.7150,  0.6751, -0.9438],
        [ 1.1003,  0.3493,  0.3594],
        [-0.8663,  0.0337,  0.7717],
        [-0.7004, -1.1063, -0.5543],
        [ 0.4439,  2.0010,  0.0628]])
tensor([[-0.7150,  0.6751, -0.9438],
        [ 1.1003,  0.3493,  0.3594],
        [-0.8663,  0.0337,  0.7717],
        [-0.7004, -1.1063, -0.5543],
        [ 0.4439,  2.0010,  0.0628]])
tensor([[-0.7150,  0.6751, -0.9438],
        [ 1.1003,  0.3493,  0.3594],
        [-0.8663,  0.0337,  0.7717],
        [-0.7004, -1.1063, -0.5543],
        [ 0.4439,  2.0010,  0.0628]])
tensor([[-0.7150,  0.6751, -0.9438],
        [ 1.1003,  0.3493,  0.3594],
        [-0.8663,  0.0337,  0.7717],
        [-0.7004, -1.1063, -0.5543],
        [ 0.4439,  2.0010,  0.0628]])


In [13]:
x = torch.randn(4, 4) # randn generate normally distributed numbers while rand generate uniformed distributed
print(x)

tensor([[ 1.5104, -0.3548,  1.7886,  0.3022],
        [ 0.4186, -1.0119, -0.4212, -1.4348],
        [ 0.1776, -1.4461,  0.3139,  0.0272],
        [-0.5850, -2.3200,  0.9425,  0.8902]])


In [14]:
print(x[:,1:-1])  # support slice like numpy

tensor([[-0.3548,  1.7886],
        [-1.0119, -0.4212],
        [-1.4461,  0.3139],
        [-2.3200,  0.9425]])


In [15]:
y = x.view(16)    # view() can resize/reshape a tensor
z = x.view(-1)    # -1 is inferred from other dimensions
u = x.view(-1, 8)
print(x.size(),y.size(),z.size(),u.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([16]) torch.Size([2, 8])


In [18]:
print(x[-1][-1].item())      # one element tensor can use item() to get its value as a Python number
print(torch.randn(1).item())

0.8902276158332825
-1.1196881532669067


In [19]:
a = torch.ones(5)
print(a)
b = a.numpy()       # use numpy() to return a numpy array
print(b)
a.add_(1)           # add_ change a
print(a)
print(b)            # b is also changed, so numpy() is a low copy of a 

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)   # this is also a low copy
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
if torch.cuda.is_available():
    device = torch.device("cuda")   # a CUDA divice object
    y = torch.ones_like(x, device=device)   # use device arg to create a tensor on gpu
    x = x.to(device)                        # or use .to('cuda')/.to(device)
    z = x + y                               # calculate on gpu
    print(z)
    print(z.to("cpu", dtype=torch.float64)) # .to(..) also can change dtype

tensor([[ 2.5104,  0.6452,  2.7886,  1.3022],
        [ 1.4186, -0.0119,  0.5788, -0.4348],
        [ 1.1776, -0.4461,  1.3139,  1.0272],
        [ 0.4150, -1.3200,  1.9425,  1.8902]], device='cuda:0')
tensor([[ 2.5104,  0.6452,  2.7886,  1.3022],
        [ 1.4186, -0.0119,  0.5788, -0.4348],
        [ 1.1776, -0.4461,  1.3139,  1.0272],
        [ 0.4150, -1.3200,  1.9425,  1.8902]], dtype=torch.float64)
